import type { Metadata } from 'next';
import localFont from 'next/font/local';
import 'primeicons/primeicons.css';
import 'primereact/resources/primereact.min.css';
import './globals.css';
import 'primereact/resources/themes/mdc-light-indigo/theme.css';
import Header from '@/app/components/layout/header';
import Footer from '@/app/components/layout/footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div className="grid grid-rows-[auto,1fr,auto] min-h-screen bg-gradient-to-b from-transparent to-black">
          <Header />

          <main className="">
            <div className="">{children}</div>
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
